services:
  - type: web
    name: efficientnet-cifar10-api
    env: python
    region: oregon  # or your preferred region
    plan: free  # or starter, etc.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: "10000"  # Optional, Render sets this automatically if you omit
